# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ preprod ]
  pull_request:
    branches: [ preprod ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy Docker Image to Heroku App
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.1
        with:
          # Email Linked to your Heroku Account
          email: 'email@gmail.com'
          formation: web
          # Heroku Dyno Formation
          # formation: # optional, default is web
          # Your Heroku API Key
          api_key: ${{ secrets.HEROKU_API_KEY }}
          # Your Heroku App Name
          app_name: foncier-publick-backend
          # Dokerfile path
          dockerfile_path: ''
          # Optional build parameters
          # options: # optional